### ISSUE TITLE
利用api.render特性来删除文件

### ISSUE THREAD

**Issue by Viggo95** [zoux/vue-template#2]
https://github.com/zoux/vue-preset/blob/47c0c38c22db56ec688cb5f0a3f665afd3f09b39/generator/index.js#L20-L24
<br>
hello，你好，咨询一下
我希望将之前插件生成的工程模板全部删除，然后把自己的template目录复制进来；和你的实现很相似
<br>
我按照你的思路，测试了如下的代码，**发现模板拷贝的时候会和已存在的文件进行merge**；请问针对类似**merge合并**的情况有什么解决措施吗
`
api.render(files => {
    Object.keys(files).forEach(path => delete files[path])
})
api.render('./template')
`

**Comment by zoux** [comment]
需要检查下你的 vue-cli 版本。

3.x 时，应该是可以正常使用的；
当前的 4.x，vue-cli 进行了一定程度的改造，对当前的 plugin / preset 有一定的影响。不久前我正在对该项目进行 4.x 升级时，发现了一个[问题](https://github.com/vuejs/vue-cli/issues/4970#issuecomment-566511411)，目前维护者表示了赞同但还没回应解决方案。

**Comment by Viggo95** [comment]
@zoux 首先感谢你的答复
<br>
我查看了一下自己的vue cli版本，确实是3.x
`
// 3.10.0

vue --version
`

「当前的 4.x，vue-cli 进行了一定程度的改造，对当前的 plugin / preset 有一定的影响。不久前我正在对该项目进行 4.x 升级时，发现了一个问题，目前维护者表示了赞同但还没回应解决方案。」
<br>
我也是今天看到了你们的讨论才想咨询一下你，因为我们的需求很类似，看你的源代码确实是这样实现的，因此想请教一下关于已存在文件和复制过程的merge问题如何处理
<br>
目前我这边测试的时候，是发现package.json是会被merge的

**Comment by zoux** [comment]
之前我确实是使用 `.forEach(path => delete files[path])` 的方式删除并迁移进自选的模版文件的。你的情况我没遇到过。

刚尝试了下，目前在 cli 3.x 中使用我这个 preset 也存在异常了。

暂时我会搁置问题，在 cli 4.x 的相关问题解决后再来完善这个项目。到时候再交流哈朋友～

**Comment by Viggo95** [comment]
好的，感谢你的回复
